// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingSystem.Persistance.Context;

#nullable disable

namespace TrainingSystem.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260209025451_seedingdata")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainingSystem.data.Models.InstructorStudent.InstructorStudent", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorStudents");

                    b.HasData(
                        new
                        {
                            StudentId = -1,
                            InstructorId = -1
                        },
                        new
                        {
                            StudentId = -2,
                            InstructorId = -2
                        },
                        new
                        {
                            StudentId = -3,
                            InstructorId = -1
                        });
                });

            modelBuilder.Entity("TrainingSystem.data.Models.StudentCourse.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = -1,
                            CourseId = -1
                        },
                        new
                        {
                            StudentId = -2,
                            CourseId = -2
                        },
                        new
                        {
                            StudentId = -3,
                            CourseId = -1
                        });
                });

            modelBuilder.Entity("Training_Center.data.Models.CourseModel.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("hours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = -2,
                            Name = "C# Basics",
                            hours = 15
                        },
                        new
                        {
                            Id = -1,
                            Name = "ASP.NET Core",
                            hours = 15
                        },
                        new
                        {
                            Id = -3,
                            Name = "EF Core Advanced",
                            hours = 19
                        });
                });

            modelBuilder.Entity("Training_Center.data.Models.InstructorModel.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CourseId = -1,
                            Email = "ali@example.com",
                            Name = "Mr. Ali",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            Id = -2,
                            CourseId = -2,
                            Email = "Mona@example.com",
                            Name = "Mrs. Mona",
                            PhoneNumber = "0123456789"
                        });
                });

            modelBuilder.Entity("Training_Center.data.Models.StudentModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "mohamed@example.com",
                            Name = "Mohamed",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            Id = -2,
                            Email = "ahmed@example.com",
                            Name = "Ahmed",
                            PhoneNumber = "0123456788"
                        },
                        new
                        {
                            Id = -3,
                            Email = "sara@example.com",
                            Name = "Sara",
                            PhoneNumber = "0123456787"
                        });
                });

            modelBuilder.Entity("TrainingSystem.data.Models.InstructorStudent.InstructorStudent", b =>
                {
                    b.HasOne("Training_Center.data.Models.InstructorModel.Instructor", "Instructor")
                        .WithMany("InstructorStudents")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training_Center.data.Models.StudentModels.Student", "Student")
                        .WithMany("InstructorStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TrainingSystem.data.Models.StudentCourse.StudentCourse", b =>
                {
                    b.HasOne("Training_Center.data.Models.CourseModel.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training_Center.data.Models.StudentModels.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Training_Center.data.Models.InstructorModel.Instructor", b =>
                {
                    b.HasOne("Training_Center.data.Models.CourseModel.Course", "Course")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Training_Center.data.Models.CourseModel.Course", b =>
                {
                    b.Navigation("CourseInstructors");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Training_Center.data.Models.InstructorModel.Instructor", b =>
                {
                    b.Navigation("InstructorStudents");
                });

            modelBuilder.Entity("Training_Center.data.Models.StudentModels.Student", b =>
                {
                    b.Navigation("InstructorStudents");

                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
